# Generated by Django 4.2.4 on 2024-01-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('opening_price', models.BooleanField()),
                ('closing_price', models.BooleanField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
